markdown: kramdown
exclude:
  - LICENSE

layouts_dir: ./_noita
baseurl: /

noita:
  name: PHP 1511 / PHP 2511 Applied Regression Analsis
  description: A first course in Regression!
  author:
    name: Adam J Sullivan
    url: https://vivo.brown.edu/display/asulliv3
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Info
        url: /
      - name: Syllabus
        url: /syllabus/
      - name: Calendar
        url: /calendar
      - name: Resources
        url: /resources/
      - name: Sakai
        url: https://sakai.duke.edu/portal/site/sta521-s17
        absolute: true
      - name: Github
        url: https://github.com/STA521-S17
        absolute: true
social:
  github: merliseclyde
  linkedin: merliseclyde
permalink: /404.html
